### ISSUE TITLE
pgdg-centos95-9.5-3.noarch.rpm 404 Not Found

### ISSUE THREAD

**Issue by maursam** [fmidev/smartmet-install#1]
Hi, thank you for an excellent tool for weather services, i have smartmet 2 years ago, but on abril th repos updates and failure macgyver, postgresq and other tools inside the smartmet enviroment.
I try to make a new install, but the repo of postgresql  pgdg-centos95-9.5-3.noarch.rpm show me the error "404 Not found".
I looking for the pgdg-centos95-9.5-3 in others repos but i haven't found it.
Thanks in advanced, may be you have other solution.

rpm -Uvh https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-
7-x86_64/pgdg-centos95-9.5-3.noarch.rpm
Retrieving https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-3
.noarch.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-
9.5-3.noarch.rpm - transfer failed

**Comment by mheiskan** [comment]
Hello,

The PGDG packages have been renamed. You can find the latest CentOS 7 RPM from

   https://yum.postgresql.org/repopackages.php

or directly from

  https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

The name should remain the same in subsequent versions. Also note that the repo-file now contains all PGDG versions from 9.4 to 12, plus a new repository called pgdg-common.

We are still transitioning to use the new repository system, but managed to build new versions using

`yum-config-manager --disable "pgdg*"`
`yum-config-manager --enable pgdg-common pgdg95`
`yum-config-manager --setopt="pgdg*.exclude=postgis*,libpqxx*" --save`

We expect to be able to build the packages using the PostGIS version packaged by PGDG in the near future, until then we're packaging our own RPMs using the version in EPEL.

**Comment by maursam** [comment]
Thank you for your answer, i installed https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-r
epo-42.0-11.noarch.rpm.
And when continue with the smartmet installation show me this Error from smartmet-library-macgyver.
Error: Package: smartmet-library-macgyver-20.4.18-1.el7.fmi.x86_64 (smartmet-open)
           Requires: libpqxx-4.0.so()(64bit)
           Available: 1:libpqxx-4.0.1-1.el7.x86_64 (epel)
               libpqxx-4.0.so()(64bit)
           Installed: 1:libpqxx-5.0.1-2.rhel7.1.x86_64 (@pgdg11)
              ~libpqxx-5.0.so()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

And if use "--skip-broken" does not install many libraries.

**Comment by mheiskan** [comment]
If you are using smartmet-open packages, the update path is now a bit more complicated since we've also moved on to Boost 1.69 from EPEL instead of using our own build.

In that case the upgrade path is something like
```
systemctl stop smartmet-server
rpm -e --nodeps libpqxx
rpm -e --nodeps libpqxx-debuginfo
yum erase 'pgdg-*'
# Replace with your own proxy if using one:
https_proxy=http://wwwcache.fmi.fi:8080 wget https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
yum localinstall pgdg-redhat-repo-latest.noarch.rpm
rm -f pgdg-redhat-repo-latest.noarch.rpm
yum-config-manager --disable "pgdg*"
yum-config-manager --enable pgdg-common pgdg95
yum-config-manager --setopt="pgdg*.exclude=postgis*,libpqxx*" --save
# Replace with your own proxy if using one:
yum-config-manager --setopt="pgdg*.proxy=http://wwwcache.fmi.fi:8080" --save
yum update "*smartmet*"
yum erase 'boost*1.66*'
systemctl daemon-reload
systemctl start smartmet-server
```
We have used the above commands successfully both on our own ~10-20 servers as well as for external installations.

**Comment by maursam** [comment]
Thank you so much for your help.
The installation is successful.
